import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Layout from '../components/Layout'


export default function Home({data}) {
  console.log(data);
  return (
    <Layout >
      <Head>
        <title>Nextjs-Movie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <h1>POPULAR FILMS</h1>
     {data.results.map(movie=>(
       <div key={movie.id}>
         <h3>{movie.title}</h3>
         <img src={`https://www.themoviedb.org/t/p/w220_and_h330_face${movie.poster_path}`} alt={movie.title} />
       </div>
     ))}

      
    </Layout>
  )
}

export async function getStaticProps(){
  const res = await fetch(`
  https://api.themoviedb.org/3/movie/popular?api_key=03bc9c0daee204f57c600a2bd683e5d9&language=en-US&page=1`)
  const data= await res.json()
  return {
    props:{
      data
    }
  }
}